version: '3.9'
services:
  #MongoDB service
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo:/data/db
  #API Service
  api:
    build: .
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017
      - DB_NAME=my_db
      - NAME=0xajinkya

volumes:
  mongo:
    driver: local